DATA SEGMENT
N EQU 0004H
R EQU 0002H
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:CODE

START:
    MOV AX,N
    MOV BX,R 
    SUB AX,BX ;AX=N-R
    MOV BX,AX ;BX=N-R
    MOV AX,0001H ;AX=1
RPT: ;FOR (N-R)!
    MUL BX ;AX=AX*N-R
    DEC BX ;N-R=N-R-1
    JNZ RPT
    MOV CX,AX ;(N-R)!
    MOV AX,0001H
    MOV BX,N
RPT1: ;FOR N!
    MUL BX ;AX=AX*N
    DEC BX ;N=N-1
    JNZ RPT1 
    DIV CX ;N!/(N-R)!
    HLT
CODE ENDS
END START